### ISSUE TITLE
Failed executing  mvn gwt:generate-module gwt:devmode

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [gwtboot/domino-rest-enum-date#2]
I have created a project based on this project and when I want to do the indicated command I get the following exception. Any ideas?
Thanks!

![image](https://user-images.githubusercontent.com/13700946/233805304-22d49930-c791-4a35-9645-b98a3598509d.png)

**Comment by RaulPampliegaMayoral** [comment]
Just my fault. I was in the wrong folder (root folder) instead of the client folder. Closing this issue

**Comment by lofidewanto** [comment]
Your error shows a wrong Maven Plugin for GWT… weird…

Are you aware of the GWT Boot Maven Archetype? You could simply use it to build your Maven project:

https://github.com/gwtboot/gwt-boot-maven-archetypes

Hope this helps!
